export const GAMEPLAY = Object.freeze({
  width: 960,
  height: 540,
  groundY: 450,
  playerX: 160,
  playerWidth: 60,
  playerHeight: 70,
  gravityY: 1800,
  jumpVelocity: -680,
  doubleJumpVelocity: -620,
  fastFallVelocity: 820,
  maxJumps: 2,
  storyTransitionScore: 1000,
  initialSpeed: 300,
  speedIncreasePerSecond: 5,
  maxSpeed: 660,
  rushMaxSpeed: 840,
  scorePerSecond: 10,
  initialSpawnDistance: 360,
  obstacleGapMin: 500,
  obstacleGapMax: 750,
  obstacleDestroyX: -100,
  farScrollFactor: 0.12,
  campusScrollFactor: 0.35,
  groundScrollFactor: 1,
});

export const COLORS = Object.freeze({
  sky: 0x87d2f3,
  skyLight: 0xe9f9ff,
  navy: 0x173c59,
  navyDark: 0x0d2a40,
  cream: 0xfff7e3,
  orange: 0xffa640,
  coral: 0xff6f61,
  mint: 0x62d5a1,
  grass: 0x76c66b,
  grassDark: 0x3f8f55,
  pavement: 0xeee8da,
  pavementDark: 0xc8c2b5,
  white: 0xffffff,
});

export const OBSTACLES = Object.freeze([
  {
    key: 'obstacle-backpack',
    label: '书包',
    width: 52,
    height: 44,
    action: 'jump',
    body: { width: 44, height: 36, offsetX: 4, offsetY: 8 },
  },
  {
    key: 'obstacle-barricade',
    label: '路障',
    width: 62,
    height: 68,
    action: 'jump',
    body: { width: 56, height: 62, offsetX: 3, offsetY: 6 },
  },
  {
    key: 'obstacle-puddle',
    label: '水坑',
    width: 82,
    height: 18,
    action: 'jump',
    body: { width: 76, height: 10, offsetX: 3, offsetY: 8 },
  },
  {
    key: 'obstacle-cone',
    label: '交通锥',
    width: 44,
    height: 62,
    action: 'jump',
    body: { width: 36, height: 58, offsetX: 4, offsetY: 4 },
  },
  {
    key: 'obstacle-books',
    label: '散落的课本',
    width: 70,
    height: 34,
    action: 'jump',
    body: { width: 64, height: 30, offsetX: 3, offsetY: 4 },
  },
  {
    key: 'obstacle-stacked-crates',
    label: '叠高的器材箱',
    width: 92,
    height: 154,
    action: 'doubleJump',
    body: { width: 82, height: 146, offsetX: 5, offsetY: 8 },
  },
  {
    key: 'obstacle-book-cart',
    label: '高书车',
    width: 108,
    height: 148,
    action: 'doubleJump',
    body: { width: 98, height: 140, offsetX: 5, offsetY: 8 },
  },
  {
    key: 'obstacle-basketball',
    label: '飞来的篮球',
    width: 56,
    height: 36,
    action: 'either',
    placement: 'air',
    y: 400,
    body: { width: 30, height: 30, offsetX: 1, offsetY: 3 },
  },
  {
    key: 'obstacle-low-banner',
    label: '低垂横幅',
    width: 78,
    height: 330,
    action: 'crouch',
    body: { width: 70, height: 288, offsetX: 4, offsetY: 0 },
  },
  {
    key: 'obstacle-low-branch',
    label: '低垂树枝',
    width: 104,
    height: 220,
    action: 'crouch',
    body: { width: 96, height: 178, offsetX: 4, offsetY: 0 },
  },
]);

export const ISEKAI_OBSTACLES = Object.freeze([
  {
    key: 'obstacle-slime',
    label: '森林史莱姆',
    width: 64,
    height: 44,
    action: 'jump',
    body: { width: 54, height: 34, offsetX: 5, offsetY: 10 },
  },
  {
    key: 'obstacle-rune-stone',
    label: '符文石碑',
    width: 62,
    height: 72,
    action: 'jump',
    body: { width: 52, height: 66, offsetX: 5, offsetY: 6 },
  },
  {
    key: 'obstacle-crystal-spire',
    label: '魔晶尖塔',
    width: 92,
    height: 156,
    action: 'doubleJump',
    body: { width: 76, height: 148, offsetX: 8, offsetY: 8 },
  },
  {
    key: 'obstacle-magic-orb',
    label: '漂浮魔球',
    width: 58,
    height: 38,
    action: 'either',
    placement: 'air',
    y: 400,
    body: { width: 30, height: 30, offsetX: 14, offsetY: 4 },
  },
  {
    key: 'obstacle-shadow-bat',
    label: '低飞影蝠',
    width: 112,
    height: 220,
    action: 'crouch',
    body: { width: 100, height: 178, offsetX: 6, offsetY: 0 },
  },
]);
